omap:iodmm Refactor iodmm code and fix compilation issue. Allow cache flush
omap:iodmm-dmm code moved to new file and fixes

The patch handles the following

	1. Moved the code out of iovmm to new file.
	2. Removed the config option related to IOVMM in makefile
	3. Moved the DMM pool creation part to iodmm.c
	4. Removed the hacks that were made to handle Tiler buffers.
	5. Only buffers that are mapped would be permittted for flushing.
	6. Removed the ioctl to program PTE entries directly from userspace.
           Regular DMM should be used to program the PTE entries. This requires
	   userspace change
	7. Removed unused functions.
	8. Provided the support to map Anonymous buffers.
	9. Provided the support to map Physical address if passed.
	10. Replaced the local spinlock with global mutex lock for critical
	   critical sections.

Signed-off-by: Hari Kanigeri <h-kanigeri2@ti.com>

omap:iodmm-resolve compilation issue

This patch resolves the following build issue that was observed
when build with omap3 defcofig.

arch/arm/plat-omap/iodmm.c: In function 'user_to_device_map':
arch/arm/plat-omap/iodmm.c:425: error: dereferencing pointer to incomplete type
arch/arm/plat-omap/iodmm.c: In function 'dmm_user':
arch/arm/plat-omap/iodmm.c:655: error: dereferencing pointer to incomplete type
arch/arm/plat-omap/iodmm.c:744: error: dereferencing pointer to incomplete type
make[1]: *** [arch/arm/plat-omap/iodmm.o] Error 1 m

Signed-off-by: Hari Kanigeri <h-kanigeri2@ti.com>

omap:iodmm-allow unconditional cache flush

This patch reverts back Russell King's patch to do the userspace
buffer cache flush. This allows unconditional cache operations and this
patch is considered as a hack patch until the new API is alinged with MM
team

Signed-off-by: Hari Kanigeri <h-kanigeri2@ti.com>