arm: Make psci_smp_available() depend on SMP + PSCI
With CONFIG_ARM_PSCI=y, CONFIG_SMP=n and CONFIG_ARCH_TEGRA_124_SOC=y I
end up with:

|arch/arm/mach-tegra/built-in.o: In function `tegra114_cpuidle_init':
|arch/arm/mach-tegra/cpuidle-tegra114.c:93: undefined reference to `psci_smp_available'
|Makefile:927: recipe for target 'vmlinux' failed

during build testing. 

Signed-off-by: Sebastian Andrzej Siewior <bigeasy@linutronix.de>